version: '3.8'

services:
  web:
    build: .
    command: gunicorn django_salary.wsgi:application --bind 0.0.0.0:8000 --workers 3
  # python manage.py runserver 0.0.0.0:8001
    # gunicorn django_salary.wsgi:application --bind 0.0.0.0:8001 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Using the .env file for environment variables

volumes:
  postgres_data:
  # db:
  #   image: postgres:12
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_DB=${DB_NAME}  # Using variables from .env file
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}


