# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - salarywebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_07f844019fc74fb081d564dd17081d1c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_82de9c7528a1447ab28291aa8fae17fa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_07f844019fc74fb081d564dd17081d1c }}/asanni2022/salaryapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'salarywebapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d5e3626ba64c46b6a323c3e6f68be472 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_07f844019fc74fb081d564dd17081d1c }}/asanni2022/salaryapp:${{ github.sha }}'